[development]
address = "0.0.0.0"
port = 8000
workers = 1
keep_alive = 5
log = "normal"
secret_key = "qmqIpu785xlcv94cHL01moqTKwD2Ji0bwEX4pKqKPwI="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
secret_key = "ykLSoHCcX9qLiZLS0zg6mQwG+mkObZ7OIqZX1hma5Gs="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "critical"
secret_key = "Dn78BvF4RpRdgo05hJR3mzMtxdbH4+o0tEB6kBdJKo8="
limits = { forms = 32768 }