[development]
address = "0.0.0.0"
port = 10425
workers = 4
keep_alive = 5
log = "normal"
secret_key = "qmqIpu785xlcv94cHL01moqTKwD2Ji0bwEX4pKqKPwI="
limits = { json = 4073741824 }

[staging]
address = "127.0.0.1"
port = 10425
workers = 4
keep_alive = 5
log = "normal"
secret_key = "ykLSoHCcX9qLiZLS0zg6mQwG+mkObZ7OIqZX1hma5Gs="
limits = { json = 4073741824 }

[production]
address = "127.0.0.1"
port = 10425
workers = 10
keep_alive = 5
log = "normal"
secret_key = "Dn78BvF4RpRdgo05hJR3mzMtxdbH4+o0tEB6kBdJKo8="
limits = { json = 4073741824 }
